name: Compile Legende OS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Installer les outils nécessaires
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

      - name: Installer l'outil Repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Télécharger le code source
        run: |
          mkdir workspace
          cd workspace
          repo init -u https://android.googlesource.com/platform/manifest -b android-14.0.0_r1
          repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j4

      - name: Lancer la compilation
        run: |
          cd workspace
          source build/envsetup.sh
          lunch aosp_arm64-eng
          # On limite le parallélisme à 2 pour éviter le crash mémoire
          export LC_ALL=C
          make -j2
