name: Build AOSP x86_64 for VirtualBox

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
      # 1. Récupération du code source du dépôt
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Installation des dépendances système
      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison build-essential ccache curl flex g++-multilib gcc-multilib \
            git gnupg gperf lib32ncurses5-dev lib32readline-dev lib32z1-dev \
            liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 \
            libxml2-utils lzop pngcrush rsync schedtool squashfs-tools \
            xsltproc zip zlib1g-dev wget unzip python3 openjdk-11-jdk
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 3. Nettoyage disque pour gagner de l'espace (C   
