name: Compile AOSP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v4

    - name: Configurer Python 2 et installer les outils
      run: |
        sudo apt-get update
        sudo apt-get install -y python2 git-core gnupg flex bison build-essential zip curl zlib1g-dev lib32z1-dev lib32ncurses5-dev x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc
        sudo ln -sf /usr/bin/python2 /usr/bin/python

    - name: Installer l'outil Repo de Google
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "PATH=~/bin:$PATH" >> $GITHUB_ENV

    - name: Télécharger le code source Android 9
      run: |
        git config --global user.name "wix000legende"
        git config --global user.email "contact@example.com"
        mkdir aosp && cd aosp
        ~/bin/repo init -u https://android.googlesource.com/platform/manifest -b android-9.0.0_r61 --depth=1
        ~/bin/repo sync -c -j8

    - name: Lancer la compilation
      run: |
        cd aosp
        source build/envsetup.sh
        lunch aosp_arm64-userdebug
        make -j8
